In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
pip install googlemaps

Collecting googlemaps
  Downloading googlemaps-4.5.3.tar.gz (32 kB)
Requirement already satisfied: requests<3.0,>=2.20.0 in /usr/local/lib/python3.7/dist-packages (from googlemaps) (2.23.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (2021.10.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (2.10)
Building wheels for collected packages: googlemaps
  Building wheel for googlemaps (setup.py) ... done
  Created wheel for googlemaps: filename=googlemaps-4.5.3-py3-none-any.whl size=38479 sha256=e02a9201121ef8c1819943cf183fa0f91c1d5e840a810aac0f63e968537c5c18
  Stored in directory: /root/.cache/pip/wheels/fa/1a/1c/cc0b8a1652a3f06aea586b0e4714a81bafed830513969baf92
Successfully built googlemaps
Installing collected packages: googlemaps
Successfully installed googlemaps-4.5.3

In [ ]:
import time
import googlemaps
import pandas as pd

In [ ]:
g_API = "Your-API-Key"
gmaps_key = googlemaps.Client(key=g_API)

In [ ]:
locations = pd.read_csv('/content/drive/MyDrive/Lok Sabha Data/Location data/LS16_location_data.csv')

In [ ]:
coordinates = list()
frequencies = dict()
notFound = list()

In [ ]:
start_time = time.time()

In [ ]:
for index,loc in enumerate(locations['location'].values):
  response = gmaps_key.geocode(loc)
  if len(response)>0:
    print(index, "found")
    coordinates.append([loc, response[0]['formatted_address'], response[0]['geometry']['location']['lat'], response[0]['geometry']['location']['lng']])

    if response[0]['formatted_address'] in frequencies.keys():
      frequencies[response[0]['formatted_address']] += locations.iloc[index]['frequency']
    else:
      frequencies[response[0]['formatted_address']] = locations.iloc[index]['frequency']
  else:
    notFound.append(index)
    print(index, "not found")
  print(f"Total : {index+1-len(notFound)}/{index+1}")
  print("Time elapsed :", time.time()-start_time)
  print("\n----------------------------------\n")

  if (index%1000)==0:
    plot_data = pd.DataFrame(coordinates, columns=['actual_address', 'formatted_address', 'latitude', 'longitude'])
    plot_data.drop_duplicates(subset=['formatted_address'], inplace=True, ignore_index=True)

    freqs = list()

    for loc in plot_data['formatted_address'].values:
        freqs.append(frequencies[loc])

    plot_data.insert(4, "Frequency", freqs, True)
    plot_data.to_csv('/content/drive/MyDrive/Lok Sabha Data/Location data/LS16_plot_data.csv')

    not_found_locations = list()
    for index in notFound:
        not_found_locations.append(locations.iloc[index]['location'])

    not_found = pd.DataFrame()
    not_found.insert(0, "index", notFound, True)
    not_found.insert(1, "location", not_found_locations, True)

    not_found.to_csv('/content/drive/MyDrive/Lok Sabha Data/Location data/LS16_not_found.csv')
    print(f"Saved after {index}")

Streaming output truncated to the last 5000 lines.

10308 not found
Total : 9743/10309
Time elapsed : 4478.548222064972

----------------------------------

10309 found
Total : 9744/10310
Time elapsed : 4478.90074634552

----------------------------------

10310 not found
Total : 9744/10311
Time elapsed : 4479.598046541214

----------------------------------

10311 found
Total : 9745/10312
Time elapsed : 4479.949809074402

----------------------------------

10312 found
Total : 9746/10313
Time elapsed : 4480.311680555344

----------------------------------

10313 found
Total : 9747/10314
Time elapsed : 4480.542938709259

----------------------------------

10314 found
Total : 9748/10315
Time elapsed : 4481.041374206543

----------------------------------

10315 found
Total : 9749/10316
Time elapsed : 4485.480474233627

----------------------------------

10316 found
Total : 9750/10317
Time elapsed : 4485.69167470932

----------------------------------

10317 found
Total : 9751/10318
Time elapsed : 4486.107860803604

----------------------------------

10318 found
Total : 9752/10319
Time elapsed : 4486.531365156174

----------------------------------

10319 found
Total : 9753/10320
Time elapsed : 4486.769523859024

----------------------------------

10320 found
Total : 9754/10321
Time elapsed : 4491.877605199814

----------------------------------

10321 found
Total : 9755/10322
Time elapsed : 4492.349578380585

----------------------------------

10322 found
Total : 9756/10323
Time elapsed : 4492.719125032425

----------------------------------

10323 found
Total : 9757/10324
Time elapsed : 4493.075224876404

----------------------------------

10324 found
Total : 9758/10325
Time elapsed : 4493.4820692539215

----------------------------------

10325 found
Total : 9759/10326
Time elapsed : 4494.135000228882

----------------------------------

10326 found
Total : 9760/10327
Time elapsed : 4494.60280418396

----------------------------------

10327 found
Total : 9761/10328
Time elapsed : 4494.89851641655

----------------------------------

10328 found
Total : 9762/10329
Time elapsed : 4495.353134393692

----------------------------------

10329 found
Total : 9763/10330
Time elapsed : 4495.69890499115

----------------------------------

10330 found
Total : 9764/10331
Time elapsed : 4496.220060348511

----------------------------------

10331 found
Total : 9765/10332
Time elapsed : 4496.704813241959

----------------------------------

10332 found
Total : 9766/10333
Time elapsed : 4497.052682638168

----------------------------------

10333 found
Total : 9767/10334
Time elapsed : 4497.297655105591

----------------------------------

10334 found
Total : 9768/10335
Time elapsed : 4498.252656698227

----------------------------------

10335 found
Total : 9769/10336
Time elapsed : 4498.469616651535

----------------------------------

10336 found
Total : 9770/10337
Time elapsed : 4498.840450763702

----------------------------------

10337 found
Total : 9771/10338
Time elapsed : 4499.205828428268

----------------------------------

10338 found
Total : 9772/10339
Time elapsed : 4499.558522939682

----------------------------------

10339 found
Total : 9773/10340
Time elapsed : 4499.748857021332

----------------------------------

10340 found
Total : 9774/10341
Time elapsed : 4499.984332084656

----------------------------------

10341 found
Total : 9775/10342
Time elapsed : 4500.331185102463

----------------------------------

10342 found
Total : 9776/10343
Time elapsed : 4500.866094589233

----------------------------------

10343 found
Total : 9777/10344
Time elapsed : 4501.090017557144

----------------------------------

10344 found
Total : 9778/10345
Time elapsed : 4501.285739183426

----------------------------------

10345 found
Total : 9779/10346
Time elapsed : 4501.698861122131

----------------------------------

10346 found
Total : 9780/10347
Time elapsed : 4502.146248102188

----------------------------------

10347 found
Total : 9781/10348
Time elapsed : 4502.63679933548

----------------------------------

10348 found
Total : 9782/10349
Time elapsed : 4503.037272930145

----------------------------------

10349 found
Total : 9783/10350
Time elapsed : 4503.467818021774

----------------------------------

10350 found
Total : 9784/10351
Time elapsed : 4503.6976273059845

----------------------------------

10351 found
Total : 9785/10352
Time elapsed : 4504.100874423981

----------------------------------

10352 found
Total : 9786/10353
Time elapsed : 4504.591177225113

----------------------------------

10353 found
Total : 9787/10354
Time elapsed : 4505.669302225113

----------------------------------

10354 found
Total : 9788/10355
Time elapsed : 4506.051986217499

----------------------------------

10355 found
Total : 9789/10356
Time elapsed : 4506.640820980072

----------------------------------

10356 found
Total : 9790/10357
Time elapsed : 4506.906515836716

----------------------------------

10357 found
Total : 9791/10358
Time elapsed : 4507.277107954025

----------------------------------

10358 found
Total : 9792/10359
Time elapsed : 4507.47266292572

----------------------------------

10359 found
Total : 9793/10360
Time elapsed : 4507.670487880707

----------------------------------

10360 found
Total : 9794/10361
Time elapsed : 4508.2923357486725

----------------------------------

10361 found
Total : 9795/10362
Time elapsed : 4508.774030447006

----------------------------------

10362 found
Total : 9796/10363
Time elapsed : 4509.132949113846

----------------------------------

10363 found
Total : 9797/10364
Time elapsed : 4509.625020265579

----------------------------------

10364 found
Total : 9798/10365
Time elapsed : 4509.835188865662

----------------------------------

10365 not found
Total : 9798/10366
Time elapsed : 4510.509497880936

----------------------------------

10366 found
Total : 9799/10367
Time elapsed : 4510.873781442642

----------------------------------

10367 found
Total : 9800/10368
Time elapsed : 4511.0829491615295

----------------------------------

10368 found
Total : 9801/10369
Time elapsed : 4511.600423812866

----------------------------------

10369 not found
Total : 9801/10370
Time elapsed : 4511.9638702869415

----------------------------------

10370 found
Total : 9802/10371
Time elapsed : 4512.452440261841

----------------------------------

10371 found
Total : 9803/10372
Time elapsed : 4512.863240242004

----------------------------------

10372 found
Total : 9804/10373
Time elapsed : 4513.2299926280975

----------------------------------

10373 not found
Total : 9804/10374
Time elapsed : 4513.604379653931

----------------------------------

10374 found
Total : 9805/10375
Time elapsed : 4513.973926305771

----------------------------------

10375 found
Total : 9806/10376
Time elapsed : 4514.330840826035

----------------------------------

10376 found
Total : 9807/10377
Time elapsed : 4514.653834819794

----------------------------------

10377 found
Total : 9808/10378
Time elapsed : 4515.183683872223

----------------------------------

10378 not found
Total : 9808/10379
Time elapsed : 4515.449337005615

----------------------------------

10379 found
Total : 9809/10380
Time elapsed : 4515.886253356934

----------------------------------

10380 found
Total : 9810/10381
Time elapsed : 4516.165600061417

----------------------------------

10381 found
Total : 9811/10382
Time elapsed : 4516.751362085342

----------------------------------

10382 found
Total : 9812/10383
Time elapsed : 4517.078448295593

----------------------------------

10383 found
Total : 9813/10384
Time elapsed : 4517.615203857422

----------------------------------

10384 found
Total : 9814/10385
Time elapsed : 4518.171896696091

----------------------------------

10385 found
Total : 9815/10386
Time elapsed : 4518.433765888214

----------------------------------

10386 found
Total : 9816/10387
Time elapsed : 4518.952921390533

----------------------------------

10387 found
Total : 9817/10388
Time elapsed : 4519.371561527252

----------------------------------

10388 found
Total : 9818/10389
Time elapsed : 4519.76029086113

----------------------------------

10389 found
Total : 9819/10390
Time elapsed : 4520.255108118057

----------------------------------

10390 found
Total : 9820/10391
Time elapsed : 4520.638689517975

----------------------------------

10391 found
Total : 9821/10392
Time elapsed : 4520.845954418182

----------------------------------

10392 found
Total : 9822/10393
Time elapsed : 4521.076009750366

----------------------------------

10393 found
Total : 9823/10394
Time elapsed : 4521.675641536713

----------------------------------

10394 found
Total : 9824/10395
Time elapsed : 4521.88786149025

----------------------------------

10395 found
Total : 9825/10396
Time elapsed : 4522.336248159409

----------------------------------

10396 found
Total : 9826/10397
Time elapsed : 4523.675141811371

----------------------------------

10397 found
Total : 9827/10398
Time elapsed : 4524.115929365158

----------------------------------

10398 found
Total : 9828/10399
Time elapsed : 4524.696154356003

----------------------------------

10399 found
Total : 9829/10400
Time elapsed : 4524.925370693207

----------------------------------

10400 found
Total : 9830/10401
Time elapsed : 4525.467931032181

----------------------------------

10401 found
Total : 9831/10402
Time elapsed : 4525.97362112999

----------------------------------

10402 found
Total : 9832/10403
Time elapsed : 4526.2457547187805

----------------------------------

10403 found
Total : 9833/10404
Time elapsed : 4527.137248039246

----------------------------------

10404 found
Total : 9834/10405
Time elapsed : 4527.421068906784

----------------------------------

10405 found
Total : 9835/10406
Time elapsed : 4527.81262421608

----------------------------------

10406 found
Total : 9836/10407
Time elapsed : 4528.357800483704

----------------------------------

10407 found
Total : 9837/10408
Time elapsed : 4528.656779050827

----------------------------------

10408 found
Total : 9838/10409
Time elapsed : 4529.000627756119

----------------------------------

10409 found
Total : 9839/10410
Time elapsed : 4529.436095952988

----------------------------------

10410 found
Total : 9840/10411
Time elapsed : 4529.779333114624

----------------------------------

10411 not found
Total : 9840/10412
Time elapsed : 4530.379460096359

----------------------------------

10412 found
Total : 9841/10413
Time elapsed : 4530.820887327194

----------------------------------

10413 found
Total : 9842/10414
Time elapsed : 4531.057507276535

----------------------------------

10414 found
Total : 9843/10415
Time elapsed : 4531.303927183151

----------------------------------

10415 found
Total : 9844/10416
Time elapsed : 4531.933164834976

----------------------------------

10416 found
Total : 9845/10417
Time elapsed : 4532.573768854141

----------------------------------

10417 found
Total : 9846/10418
Time elapsed : 4532.874664068222

----------------------------------

10418 found
Total : 9847/10419
Time elapsed : 4533.507643938065

----------------------------------

10419 found
Total : 9848/10420
Time elapsed : 4533.884915590286

----------------------------------

10420 found
Total : 9849/10421
Time elapsed : 4534.2159786224365

----------------------------------

10421 found
Total : 9850/10422
Time elapsed : 4534.631834983826

----------------------------------

10422 found
Total : 9851/10423
Time elapsed : 4535.017981767654

----------------------------------

10423 found
Total : 9852/10424
Time elapsed : 4535.223965167999

----------------------------------

10424 found
Total : 9853/10425
Time elapsed : 4536.241099596024

----------------------------------

10425 found
Total : 9854/10426
Time elapsed : 4536.946093082428

----------------------------------

10426 found
Total : 9855/10427
Time elapsed : 4537.302994728088

----------------------------------

10427 found
Total : 9856/10428
Time elapsed : 4537.674669265747

----------------------------------

10428 found
Total : 9857/10429
Time elapsed : 4538.130797863007

----------------------------------

10429 found
Total : 9858/10430
Time elapsed : 4538.547310113907

----------------------------------

10430 found
Total : 9859/10431
Time elapsed : 4538.931833982468

----------------------------------

10431 found
Total : 9860/10432
Time elapsed : 4539.258810043335

----------------------------------

10432 found
Total : 9861/10433
Time elapsed : 4539.717574834824

----------------------------------

10433 not found
Total : 9861/10434
Time elapsed : 4539.896289348602

----------------------------------

10434 found
Total : 9862/10435
Time elapsed : 4540.311641216278

----------------------------------

10435 found
Total : 9863/10436
Time elapsed : 4540.721124172211

----------------------------------

10436 found
Total : 9864/10437
Time elapsed : 4541.148015975952

----------------------------------

10437 found
Total : 9865/10438
Time elapsed : 4541.637479305267

----------------------------------

10438 found
Total : 9866/10439
Time elapsed : 4541.819397211075

----------------------------------

10439 found
Total : 9867/10440
Time elapsed : 4542.271162033081

----------------------------------

10440 found
Total : 9868/10441
Time elapsed : 4542.643744945526

----------------------------------

10441 found
Total : 9869/10442
Time elapsed : 4547.269164323807

----------------------------------

10442 found
Total : 9870/10443
Time elapsed : 4547.835076808929

----------------------------------

10443 found
Total : 9871/10444
Time elapsed : 4548.191455125809

----------------------------------

10444 found
Total : 9872/10445
Time elapsed : 4548.683373451233

----------------------------------

10445 found
Total : 9873/10446
Time elapsed : 4549.0220782756805

----------------------------------

10446 found
Total : 9874/10447
Time elapsed : 4549.521322965622

----------------------------------

10447 found
Total : 9875/10448
Time elapsed : 4549.987951040268

----------------------------------

10448 found
Total : 9876/10449
Time elapsed : 4550.472814798355

----------------------------------

10449 found
Total : 9877/10450
Time elapsed : 4551.178817033768

----------------------------------

10450 found
Total : 9878/10451
Time elapsed : 4551.571662187576

----------------------------------

10451 found
Total : 9879/10452
Time elapsed : 4551.770857334137

----------------------------------

10452 found
Total : 9880/10453
Time elapsed : 4553.746588945389

----------------------------------

10453 found
Total : 9881/10454
Time elapsed : 4554.165062904358

----------------------------------

10454 found
Total : 9882/10455
Time elapsed : 4554.5527584552765

----------------------------------

10455 found
Total : 9883/10456
Time elapsed : 4555.33341383934

----------------------------------

10456 found
Total : 9884/10457
Time elapsed : 4557.548000574112

----------------------------------

10457 found
Total : 9885/10458
Time elapsed : 4557.942211389542

----------------------------------

10458 found
Total : 9886/10459
Time elapsed : 4558.276880502701

----------------------------------

10459 found
Total : 9887/10460
Time elapsed : 4558.723341464996

----------------------------------

10460 found
Total : 9888/10461
Time elapsed : 4559.098212718964

----------------------------------

10461 found
Total : 9889/10462
Time elapsed : 4559.5588047504425

----------------------------------

10462 found
Total : 9890/10463
Time elapsed : 4560.018669843674

----------------------------------

10463 found
Total : 9891/10464
Time elapsed : 4560.426871299744

----------------------------------

10464 found
Total : 9892/10465
Time elapsed : 4560.889622449875

----------------------------------

10465 found
Total : 9893/10466
Time elapsed : 4561.315164089203

----------------------------------

10466 found
Total : 9894/10467
Time elapsed : 4561.776794910431

----------------------------------

10467 found
Total : 9895/10468
Time elapsed : 4561.973928451538

----------------------------------

10468 found
Total : 9896/10469
Time elapsed : 4562.621071815491

----------------------------------

10469 found
Total : 9897/10470
Time elapsed : 4562.9717853069305

----------------------------------

10470 found
Total : 9898/10471
Time elapsed : 4563.4168174266815

----------------------------------

10471 found
Total : 9899/10472
Time elapsed : 4564.271777391434

----------------------------------

10472 found
Total : 9900/10473
Time elapsed : 4564.784285783768

----------------------------------

10473 found
Total : 9901/10474
Time elapsed : 4565.38786482811

----------------------------------

10474 found
Total : 9902/10475
Time elapsed : 4566.359374284744

----------------------------------

10475 found
Total : 9903/10476
Time elapsed : 4566.766577720642

----------------------------------

10476 found
Total : 9904/10477
Time elapsed : 4567.151138544083

----------------------------------

10477 found
Total : 9905/10478
Time elapsed : 4567.591781377792

----------------------------------

10478 found
Total : 9906/10479
Time elapsed : 4567.79030752182

----------------------------------

10479 found
Total : 9907/10480
Time elapsed : 4568.171835422516

----------------------------------

10480 found
Total : 9908/10481
Time elapsed : 4568.636915445328

----------------------------------

10481 found
Total : 9909/10482
Time elapsed : 4568.996746301651

----------------------------------

10482 found
Total : 9910/10483
Time elapsed : 4569.213838100433

----------------------------------

10483 found
Total : 9911/10484
Time elapsed : 4569.709925413132

----------------------------------

10484 found
Total : 9912/10485
Time elapsed : 4569.952621221542

----------------------------------

10485 found
Total : 9913/10486
Time elapsed : 4570.394326925278

----------------------------------

10486 found
Total : 9914/10487
Time elapsed : 4570.604944467545

----------------------------------

10487 not found
Total : 9914/10488
Time elapsed : 4570.873480081558

----------------------------------

10488 found
Total : 9915/10489
Time elapsed : 4571.314876794815

----------------------------------

10489 found
Total : 9916/10490
Time elapsed : 4571.64284324646

----------------------------------

10490 found
Total : 9917/10491
Time elapsed : 4572.111825466156

----------------------------------

10491 found
Total : 9918/10492
Time elapsed : 4572.46834564209

----------------------------------

10492 found
Total : 9919/10493
Time elapsed : 4572.879498958588

----------------------------------

10493 found
Total : 9920/10494
Time elapsed : 4573.511784553528

----------------------------------

10494 found
Total : 9921/10495
Time elapsed : 4573.893043279648

----------------------------------

10495 found
Total : 9922/10496
Time elapsed : 4574.158846616745

----------------------------------

10496 found
Total : 9923/10497
Time elapsed : 4574.582602024078

----------------------------------

10497 found
Total : 9924/10498
Time elapsed : 4575.333910226822

----------------------------------

10498 found
Total : 9925/10499
Time elapsed : 4575.897614479065

----------------------------------

10499 found
Total : 9926/10500
Time elapsed : 4576.80304980278

----------------------------------

10500 found
Total : 9927/10501
Time elapsed : 4577.4464700222015

----------------------------------

10501 found
Total : 9928/10502
Time elapsed : 4578.601378917694

----------------------------------

10502 found
Total : 9929/10503
Time elapsed : 4578.968442201614

----------------------------------

10503 found
Total : 9930/10504
Time elapsed : 4579.608523368835

----------------------------------

10504 found
Total : 9931/10505
Time elapsed : 4580.032789707184

----------------------------------

10505 found

In [ ]:
coordinates

[['Maharashtra', 'Maharashtra, India', 19.7514798, 75.7138884],
 ['Rajasthan', 'Rajasthan, India', 27.0238036, 74.21793260000001],
 ['States', 'United States', 37.09024, -95.712891],
 ['the State of Maharashtra', 'Maharashtra, India', 19.7514798, 75.7138884],
 ['the Union Territories',
  'Landon Ln, Evansville, IN 47720, USA',
  38.0055462,
  -87.62237259999999],
 ['Karnataka', 'Karnataka, India', 15.3172775, 75.7138884],
 ['9 States', 'United States', 37.09024, -95.712891],
 ['AAREY colony',
  'Aarey Colony, Goregaon, Mumbai, Maharashtra, India',
  19.1509655,
  72.8831294],
 ['AIAIDMK',
  '226, Avvai Shanmugam Salai, Duraisamy Nagar, Royapettah, Chennai, Tamil Nadu 600014, India',
  12.9535373,
  80.1869445],
 ['Abhiyan',
  'Flat no 12-A Pocket, B-6, Pocket B 6, Mayur Vihar Phase III, Gharoli, Delhi, 110096, India',
  28.6173292,
  77.3369293],
 ['Adivasiin',
  'Mandaar,Tejgadh, Vadodara, Gujarat 391156, India',
  22.357522,
  73.9136609],
 ['Adoor', 'Adoor, Kerala, India', 9.1529667, 76.7356123],
 ['Akashvani',
  'hi1, Akashvani Bhavan, Sansad Marg, Pandit Pant Marg Area, Sansad Marg Area, New Delhi, Delhi 11000, India',
  28.6207362,
  77.2104134],
 ['Akashvaniis',
  'hi1, Akashvani Bhavan, Sansad Marg, Pandit Pant Marg Area, Sansad Marg Area, New Delhi, Delhi 11000, India',
  28.6207362,
  77.2104134],
 ['Anchuthengu', 'Anchuthengu, Kerala, India', 8.673439, 76.7581794],
 ['Andhra Pradesh', 'Andhra Pradesh, India', 15.9128998, 79.7399875],
 ['Angamali', 'Angamaly, Kerala, India', 10.1926394, 76.3869289],
 ['Anjengo', 'Anchuthengu, Kerala, India', 8.673439, 76.7581794],
 ['Antyodaya',
  '601, Palladium Business Hub, above Pantaloons, Mahavirnagar, Harikurpa Society, Chandkheda, Ahmedabad, Gujarat 380005, India',
  23.1036767,
  72.59403250000001],
 ['Arunachal Pradesh', 'Arunachal Pradesh, India', 28.2179994, 94.7277528],
 ['Assam', 'Assam, India', 26.2006043, 92.9375739],
 ['Assamand',
  '101 Independence Ave SE, Washington, DC 20540, USA',
  38.888684,
  -77.004719],
 ['Atalji',
  'Jakkuru Main Rd, Jakkuru, Bengaluru, Karnataka 560064, India',
  13.0794176,
  77.6074549],
 ['Attingal', 'Attingal, Kerala, India', 8.6982226, 76.8136569],
 ['Australia', 'Australia', -25.274398, 133.775136],
 ['Ayathil', 'Ayathil, Kottamkara, Kerala, India', 8.8965736, 76.6354952],
 ['BAHARAMPUR', 'Berhampore, West Bengal, India', 24.0982607, 88.268411],
 ['BALASORE', 'Balasore, Odisha, India', 21.4933578, 86.9134794],
 ['Bangladesh', 'Bangladesh', 23.684994, 90.356331],
 ['Bengal', 'West Bengal, India', 22.9867569, 87.8549755],
 ['Bengaluruand', 'Bengaluru, Karnataka, India', 12.9715987, 77.5945627],
 ['Bharatiya',
  '1612 County Line Rd, Montgomeryville, PA 18936, USA',
  40.2492824,
  -75.20218849999999],
 ['Bhutan', 'Bhutan', 27.514162, 90.433601],
 ['Bima Yojana',
  'State Nodal Agency, O/o Director General Health, Danda Lakhaund, Sahastra Dhara, Govind Vihar, Dehradun, Uttarakhand 248013, India',
  30.3584254,
  78.09657700000001],
 ['Bisonvalley', 'Bison Valley, Kerala 685565, India', 10.0061966, 77.1132792],
 ['Brahmaputra', 'Brahmaputra', 26.4946722, 92.5249403],
 ['CaeSe', '95, 77534 Cancún, Q.R., Mexico', 21.1457254, -86.8590148],
 ['Chennai', 'Chennai, Tamil Nadu, India', 13.0826802, 80.2707184],
 ['Chhattisgarh', 'Chhattisgarh, India', 21.2786567, 81.8661442],
 ['China', 'China', 35.86166, 104.195397],
 ['Chinacombined',
  '11661 E 13th St N, Wichita, KS 67206, USA',
  37.708009,
  -97.2028181],
 ['Chinnakkanal', 'Chinnakanal, Kerala, India', 10.0367695, 77.1772737],
 ['Chirayinkeezhu', 'Chirayinkeezhu, Kerala, India', 8.7156305, 76.8490328],
 ['Coimbatore', 'Coimbatore, Tamil Nadu, India', 11.0168445, 76.9558321],
 ['Constituency Sindhudurg',
  'Ratnagiri ?Sindhudur, Maharashtra',
  16.7144944,
  73.55941279999999],
 ['Devikulam', 'Devikulam, Kerala, India', 10.0564306, 77.1197521],
 ['Dibrugarh', 'Dibrugarh, Assam, India', 27.4728327, 94.9119621],
 ['Divangjans',
  'House No. 16, Puberun Nagar, bye lane, 5, Satgaon Rail line, Puberun Nagar, Kalitakuchi, Narengi Tinali, Guwahati, Assam 781171, India',
  26.1674277,
  91.8336199],
 ['Divyang',
  '750 Fletcher Dr Suite 200, Elgin, IL 60123, USA',
  42.0532067,
  -88.3347395],
 ['Divyangjan',
  'NIMH Building, Plot No. 44-A, First Floor, C Block, Sector 40, Noida, Uttar Pradesh 201303, India',
  28.5630138,
  77.35601919999999],
 ['Divyangjans',
  'House No. 16, Puberun Nagar, bye lane, 5, Satgaon Rail line, Puberun Nagar, Kalitakuchi, Narengi Tinali, Guwahati, Assam 781171, India',
  26.1674277,
  91.8336199],
 ['Divyangjansat',
  'basti vikas kender indira nehru, Ambedkar Camp, Dilshad Garden, Delhi, Uttar Pradesh 110095, India',
  28.6850811,
  77.3316146],
 ['Doordarshan',
  'Copernicus Marg, Mahatma Jyoti Rao Phule Marg Area, New Delhi, Delhi 110001, India',
  28.6236975,
  77.2327456],
 ['Erode', 'Erode, Tamil Nadu, India', 11.3410364, 77.7171642],
 ['Farmerfraternity',
  '1021 Jefferson St, Kansas City, MO 64105, USA',
  39.1015819,
  -94.59192829999999],
 ['Foreg',
  '4000 Arlington Blvd, Arlington, VA 22204, USA',
  38.8677749,
  -77.1017128],
 ['Gandhiji',
  'Mahatma Gandhiji, Sector 10, Gandhinagar, Gujarat 382011',
  23.2201308,
  72.6549241],
 ['Geneva', 'Geneva, Switzerland', 46.2043907, 6.1431577],
 ['Gram Panchayats',
  'Bineka Road, Binaika, Madhya Pradesh 481661, India',
  22.6213885,
  80.393819],
 ['Guntur', 'Guntur, Andhra Pradesh, India', 16.3066525, 80.4365402],
 ['Guwahati', 'Guwahati, Assam, India', 26.1445169, 91.7362365],
 ['HighCourt',
  '385 Broadway, New York, NY 10013, USA',
  40.7183748,
  -74.0030721],
 ["Hon'ble",
  'High court, road, Lakkar Mandi, Janipur, Jammu, Jammu and Kashmir 180007',
  32.7594363,
  74.85579659999999],
 ['Hon’ble',
  'High court, road, Lakkar Mandi, Janipur, Jammu, Jammu and Kashmir 180007',
  32.7594363,
  74.85579659999999],
 ['Hyderabad', 'Hyderabad, Telangana, India', 17.385044, 78.486671],
 ['INDIA', 'India', 20.593684, 78.96288],
 ['ImaMarket of Manipur',
  'Market Complex, Kangla, Imphal, Manipur 795001, India',
  24.8076864,
  93.9372525],
 ['India', 'India', 20.593684, 78.96288],
 ['Indiais', 'India', 20.593684, 78.96288],
 ['Indiantalent',
  '15 The Queensway, Toronto, ON M6S 5A7, Canada',
  43.6372626,
  -79.4679457],
 ['Indonesia', 'Indonesia', -0.789275, 113.921327],
 ['Jammu', 'Jammu', 32.7266016, 74.8570259],
 ['Jan Dhan',
  '7V88+V2H, Nua, Uttar Pradesh 224132, India',
  40.2671941,
  -86.1349017],
 ['Japan', 'Japan', 36.204824, 138.252924],
 ['Jharkhand', 'Jharkhand, India', 23.6101808, 85.2799354],
 ['KOLKATA', 'Kolkata, West Bengal, India', 22.572646, 88.36389500000001],
 ['Kallumthazham',
  'Kallumthazham, Mangad, Kollam, Kerala 691019, India',
  8.9041751,
  76.6228227],
 ['Karimnagar', 'Karimnagar, Telangana, India', 18.4385553, 79.1288412],
 ['Katra', '217 Bowery, New York, NY 10002, USA', 40.7216929, -73.9931265],
 ['KendriyaVidhyala', 'Wichita, KS 67202, USA', 37.6882411, -97.3326874],
 ['KendriyaVidyalaya', 'Wichita, KS 67202, USA', 37.6882411, -97.3326874],
 ['Kendu',
  '1001 Santa Clara Ave, Alameda, CA 94501, USA',
  37.77336500000001,
  -122.268333],
 ['Kenduleaf',
  'RWHG+V75, Manamunda, Odisha 762016, India',
  20.829644,
  83.9257233],
 ['Kerala', 'Kerala, India', 10.8505159, 76.2710833],
 ['Khelo', 'Khailo, Odisha 758082, India', 21.1716568, 85.9617466],
 ['Kochi',
  '652 10th Ave, New York, NY 10036, USA',
  40.7619926,
  -73.99346919999999],
 ['Kolkata', 'Kolkata, West Bengal, India', 22.572646, 88.36389500000001],
 ['Kongu',
  '7JF4+MR6, Thoppupalayam, Perundurai, Tamil Nadu 638060, India',
  11.2741632,
  77.6070273],
 ['Kuttampuzha', 'Kuttampuzha, Kerala 686681, India', 10.15246, 76.7395994],
 ['Lok Sabha',
  'Sansad Marg, Gokul Nagar, Janpath, Connaught Place, New Delhi, Delhi 110001, India',
  28.6176292,
  77.2084248],
 ['Madhya Pradesh', 'Madhya Pradesh, India', 22.9734229, 78.6568942],
 ['Maharashtra State  Mysuggestion',
  'Maharashtra, India',
  19.7514798,
  75.7138884],
 ['Maldives', 'Maldives', 3.202778, 73.22068],
 ['Manchester', 'Manchester, UK', 53.4807593, -2.2426305],
 ['Manipur', 'Manipur, India', 24.6637173, 93.90626879999999],
 ['Manipurin', 'Manipur, India', 24.6637173, 93.90626879999999],
 ['Mankulam', 'Mankulam, Kerala 685561, India', 10.117255, 76.9268541],
 ['Marayoor', 'Marayoor, Kerala 685620, India', 10.2761663, 77.161458],
 ['Meghalaya', 'Meghalaya, India', 25.4670308, 91.366216],
 ['Mizoram', 'Mizoram, India', 23.164543, 92.9375739],
 ['Mudra',
  '60 Av. Principale, Rouyn-Noranda, QC J9X 4P2, Canada',
  48.2414125,
  -79.02024159999999],
 ['Mumbai', 'Mumbai, Maharashtra, India', 19.0759837, 72.8776559],
 ['Mumbai city', 'Mumbai, Maharashtra, India', 19.0759837, 72.8776559],
 ['MumbaiDistrict', 'Mumbai, Maharashtra, India', 19.0759837, 72.8776559],
 ['Mumbaifor',
  '79 N Boundary Rd, Queens, NY 11430, USA',
  40.6583263,
  -73.775893],
 ['Myanmarthrough', 'United States', 37.09024, -95.712891],
 ['Naga Hills', 'Naga Hills, Nagaland 798626, India', 26, 95],
 ['Nagapatinam', 'Nagapattinam, Tamil Nadu, India', 10.7672313, 79.8448512],
 ['Nagapattinam', 'Nagapattinam, Tamil Nadu, India', 10.7672313, 79.8448512],
 ['Nagore', 'Nagore, Nagapattinam, Tamil Nadu, India', 10.8127803, 79.8391001],
 ['Nav Bharat',
  '218, Anhil Com, Behind Ity Centre, Near Swas, Navrangpura, Shrimali Society, Navrangpura, Ahmedabad, Gujarat 380009, India',
  23.0365437,
  72.5611395],
 ['Nellore', 'Nellore, Andhra Pradesh, India', 14.4425987, 79.98645599999999],
 ['Nepal', 'Nepal', 28.394857, 84.12400799999999],
 ['New Delhi', 'New Delhi, Delhi, India', 28.6139391, 77.2090212],
 ['New India',
  '4725 Panama Ln d10, Bakersfield, CA 93313, USA',
  35.2947693,
  -119.0548749],
 ['Nigeria', 'Nigeria', 9.081999, 8.675277],
 ['Nilgiris', 'Nilgiris, Tamil Nadu, India', 11.4916043, 76.7336521],
 ['Northeastern States',
  'Northeastern United States, USA',
  43.2994285,
  -74.21793260000001],
 ['Odisha', 'Odisha, India', 20.9516658, 85.0985236],
 ['Odisha State', 'Odisha, India', 20.9516658, 85.0985236],
 ['Pakistan', 'Pakistan', 30.375321, 69.34511599999999],
 ['Palakkad', 'Palakkad, Kerala, India', 10.7867303, 76.6547932],
 ['Panchayat',
  '6, Purniya Chauraha, Sector E, Aliganj, Lucknow, Uttar Pradesh 226024, India',
  26.8922747,
  80.9439486],
 ['Panchayats',
  'Sarovar Path, Phase 8, Sector 62, Sector 62, Sahibzada Ajit Singh Nagar, Chandigarh 160062, India',
  30.6953331,
  76.72969429999999],
 ['Pattinacherry',
  'Kezhaiyore Pattinacherry, Thirumalairayan Pattinam, Puducherry 609606, India',
  10.8792277,
  79.8453717],
 ['Petroland', '3400 G. E Dr, Tyler, TX 75701, USA', 32.3113173, -95.26724],
 ['Pillaiyarpatti',
  'Pillayarpatti, Tamil Nadu, India',
  10.1205331,
  78.6668214],
 ['Punaloor', 'Punalur, Kerala, India', 9.0176117, 76.9260936],
 ['Pune', 'Pune, Maharashtra, India', 18.5204303, 73.8567437],
 ['Punjab', 'Punjab, India', 31.1471305, 75.34121789999999],
 ['PuratchiThalaivi',
  "123, Broadway High Road, Broadway, Parry's Corner, George Town, Chennai, Tamil Nadu 600108, India",
  13.0894068,
  80.2855065],
 ['RGIPTin Sivsagar',
  'Palashani, Sivasagar, Assam 785663, India',
  27.0189416,
  94.6295447],
 ['RIVER DEVELOPMENT',
  '616 Park Ave, Port Monmouth, NJ 07758, USA',
  40.4367856,
  -74.0896465],
 ['Rajya Sabha',
  '36, Pandit Pant Marg Area, Sansad Marg Area, New Delhi, Delhi 110001, India',
  28.622027,
  77.20844],
 ['Ramapuram', 'Ramapuram, Kerala, India', 9.8005152, 76.66148530000001],
 ['SOUTH GOA', 'South Goa, Goa, India', 15.11766, 74.12399599999999],
 ['Sabooj}Sathi',
  'Panipukuria Beliaberah, Baha Runa, West Bengal 721517, India',
  22.2809049,
  86.9223432],
 ['Salem', 'Salem, MA, USA', 42.51954, -70.8967155],
 ['Samajik Suraksha',
  'Bhikhanpur ( Bagduba Hat),Altapur, Karandighi, West Bengal 733215, India',
  25.743082,
  88.0322],
 ['Sanitationand',
  '121 N LaSalle St #1107, Chicago, IL 60602, USA',
  41.88389189999999,
  -87.6317127],
 ['Sathyabama',
  'SH 49A, Semmancheri, Chennai, Tamil Nadu 600119, India',
  12.8665162,
  80.2265662],
 ['ShriVajpayee',
  '132, Royal Plaza, Ved Rd, opp. Akhand Anand Collage, Industrial Area, Katargam, Surat, Gujarat 395004, India',
  21.2208891,
  72.8212681],
 ['Sivsagar', 'Sivasagar, Assam, India', 26.9826098, 94.6424521],
 ['South India', 'South India', 12.2601557, 77.1461396],
 ['Sri Lanka', 'Sri Lanka', 7.873053999999999, 80.77179699999999],
 ['Sri Lankawould', "World's End Rd, Sri Lanka", 6.7802554, 80.7944672],
 ['St Gra Ae Fa',
  '2909 M St NW, Washington, DC 20007, USA',
  38.9054258,
  -77.0584841],
 ['State Maharashtra', 'Maharashtra, India', 19.7514798, 75.7138884],
 ['State of Telanganawould',
  'Telangana, India',
  18.1124372,
  79.01929969999999],
 ['State ofAndhra Pradesh', 'Andhra Pradesh, India', 15.9128998, 79.7399875],
 ['Steel city',
  '1449 Abbott Rd, Lackawanna, NY 14218, USA',
  42.8253868,
  -78.8037296],
 ['Tamil Nadu', 'Tamil Nadu, India', 11.1271225, 78.6568942],
 ['Tamil Nadu  Coimbatore',
  'Coimbatore, Tamil Nadu, India',
  11.0168445,
  76.9558321],
 ['TamilNadu', 'Tamil Nadu, India', 11.1271225, 78.6568942],
 ['Telangana', 'Telangana, India', 18.1124372, 79.01929969999999],
 ['Textile City',
  '1575 S Gateway Rd c, Mississauga, ON L4W 5J1, Canada',
  43.6341944,
  -79.61514509999999],
 ['Thanjavur', 'Thanjavur, Tamil Nadu, India', 10.7869994, 79.13782739999999],
 ['Thanjavurconstituency',
  'Thanjavur, Tamil Nadu',
  10.5274397,
  79.29021329999999],
 ['The Government of Tamil Nadu', 'Tamil Nadu, India', 11.1271225, 78.6568942],
 ['The State of Karnataka', 'Karnataka, India', 15.3172775, 75.7138884],
 ['The State of Kerala', 'Kerala, India', 10.8505159, 76.2710833],
 ['The States of Maharashtra', 'Maharashtra, India', 19.7514798, 75.7138884],
 ['TheGovernment of Maharashtra',
  'Maharashtra, India',
  19.7514798,
  75.7138884],
 ['TheGovernmentis', 'United States', 37.09024, -95.712891],
 ['Thiruvalluvar', 'Kanyakumari, Tamil Nadu, India', 8.0778074, 77.5540357],
 ['Thiruvananthapuram',
  'Thiruvananthapuram, Kerala, India',
  8.5241391,
  76.9366376],
 ['Tier-Il',
  '2815 W Washington St, Springfield, IL 62702, USA',
  39.802152,
  -89.707574],
 ['Tinsukia', 'Tinsukia, Assam, India', 27.4885539, 95.355758],
 ['Tirupati', 'Tirupati, Andhra Pradesh, India', 13.6287557, 79.4191795],
 ['TiruppurDistrict of Tamil Nadu',
  'Tiruppur, Tamil Nadu, India',
  10.8985415,
  77.3783789],
 ['Tirupur', 'Tiruppur, Tamil Nadu, India', 11.1085242, 77.3410656],
 ['Trichy', 'Tiruchirappalli, Tamil Nadu, India', 10.7904833, 78.7046725],
 ['Tripura', 'Tripura, India', 23.9408482, 91.9881527],
 ['Tripurawere', 'Tripura, India', 23.9408482, 91.9881527],
 ['US', 'United States', 37.09024, -95.712891],
 ['USA', 'United States', 37.09024, -95.712891],
 ['Ujjala',
  '3601 13 Mile Rd, Royal Oak, MI 48073, USA',
  42.5143129,
  -83.1923522],
 ['Unani',
  '3029 Ruger Ave, Janesville, WI 53546, USA',
  42.6854152,
  -88.9822918],
 ['Uttar Pradesh', 'Uttar Pradesh, India', 26.8467088, 80.9461592],
 ['Wehad',
  '13800 N Pennsylvania Ave, Oklahoma City, OK 73134, USA',
  35.6107814,
  -97.54834919999999],
 ['West Bengal', 'West Bengal, India', 22.9867569, 87.8549755],
 ['WesternGhats',
  'Western Ghats, Kannan Devan Hills, Kerala 685561',
  10.166667,
  77.066667],
 ['Yojana',
  '30 N Michigan Ave, Chicago, IL 60602, USA',
  41.8830382,
  -87.62472559999999],
 ['areMumbai', 'Mumbai, Maharashtra, India', 19.0759837, 72.8776559],
 ['inBihar', 'Bihar, India', 25.0960742, 85.31311939999999],
 ['india', 'India', 20.593684, 78.96288],
 ['my State of Odisha', 'Odisha, India', 20.9516658, 85.0985236],
 ['onlythree States', 'United States', 37.09024, -95.712891],
 ['our State of Telangana', 'Telangana, India', 18.1124372, 79.01929969999999],
 ['the Dollar City',
  '399 Silver Dollar City Pkwy, Branson, MO 65616, USA',
  36.6670294,
  -93.33884259999999],
 ['the Lok Sabha',
  'H537+R9G, Block 5, CGHS Colony, Vasant Vihar, New Delhi, Delhi 110070, India',
  28.5545636,
  77.16343959999999],
 ['the Maharaja of Manipur',
  'Palace Compound, Wangkhei, Imphal, Manipur 795005, India',
  24.7994881,
  93.9484222],
 ['the State Governmentof Tamil Nadu',
  'Tamil Nadu, India',
  11.1271225,
  78.6568942],
 ['the State of Kerala', 'Kerala, India', 10.8505159, 76.2710833],
 ['the State of Manipur', 'Manipur, India', 24.6637173, 93.90626879999999],
 ['the State of Tamil Nadu', 'Tamil Nadu, India', 11.1271225, 78.6568942],
 ['the State of Telangana',
  'High Court Rd, Near Government City College, High Court, Ghansi Bazaar, Hyderabad, Telangana 500066, India',
  17.3693117,
  78.473056],
 ["the State of Telangana's",
  'High Court Rd, Near Government City College, High Court, Ghansi Bazaar, Hyderabad, Telangana 500066, India',
  17.3693117,
  78.473056],
 ['the State of Telanganawe',
  'High Court Rd, Near Government City College, High Court, Ghansi Bazaar, Hyderabad, Telangana 500066, India',
  17.3693117,
  78.473056],
 ['the State ofKerala', 'Kerala, India', 10.8505159, 76.2710833],
 ['the Swachh Bharat Abhiyan',
  '97HV+CVR, Govindgarh, Madhya Pradesh 486550, India',
  24.3786218,
  81.2946285],
 ['the United States', 'United States', 37.09024, -95.712891],
 ['theCapital Delhi', 'Delhi, India', 28.7040592, 77.10249019999999],
 ['theKendriyaVidyalaya',
  'Secunderabad, Staff Rd, opp. Secunderabad Club, Mudfort, Gunrock Enclave, Hyderabad, Telangana 500009, India',
  17.4522788,
  78.4957294],
 ['these Border States', 'United States', 37.09024, -95.712891],
 ['toNortheastern States',
  'Northeastern United States, USA',
  43.2994285,
  -74.21793260000001],
 ['West Bengalis', 'West Bengal, India', 22.9867569, 87.8549755],
 ['Aadharis',
  'Tilak Marg, Mandi House, New Delhi, Delhi 110001, India',
  28.6223011,
  77.2393724],
 ['Arunachal Pradeshhave', 'Arunachal Pradesh, India', 28.2179994, 94.7277528],
 ['AyushmanBharat',
  '9th Floor, Tower-l, Hanuman Road Area, Connaught Place, New Delhi, Delhi 110001, India',
  28.6283079,
  77.2154752],
 ['Gaganyaan',
  'Hofackerstrasse 33, 3645 Thun, Switzerland',
  46.729989,
  7.6249015],
 ["Hon'bleMembersin",
  '3175 Rue Saint-Jacques, Montréal, QC H4C 1G7, Canada',
  45.4834678,
  -73.5803925],
 ['Ourhard',
  '524 Oak St, Ludlow, KY 41016, USA',
  39.09143,
  -84.55283820000001],
 ['Rashtriya',
  '94, MMGS Marg, Lokmanya Tilak Colony, Dadar, Mumbai, Maharashtra 400014, India',
  19.0161115,
  72.843761],
 ['Sagarmala',
  'PTI Building, Sagarmala Cell, first floor, parliament street, Police Colony, Connaught Place, New Delhi, Delhi 110001, India',
  28.625317,
  77.214128],
 ['Barauni', 'Barauni, Bihar 851116, India', 25.4657481, 85.99139230000002],
 ['Bihar', 'Bihar, India', 25.0960742, 85.31311939999999],
 ['Bogibeelrailroad',
  'CQ55+XFF Bogibeel Bridge, Assam 786008, India',
  27.4099473,
  94.7586757],
 ['Dandi', 'Dandi, Gujarat, India', 21.3350822, 72.6225087],
 ['Delhidedicated',
  '5th Floor, Pragati Maidan, Metro Station Building Complex, Pragati Maidan, New Delhi, Delhi 110001, India',
  28.6236123,
  77.2422966],
 ['Divyangjansin',
  'NIMH Building, Plot No. 44-A, First Floor, C Block, Sector 40, Noida, Uttar Pradesh 201303, India',
  28.5630138,
  77.35601919999999],
 ['Gangaby',
  '390 N Orange Ave #1605, Orlando, FL 32801, USA',
  28.5469663,
  -81.3793527],
 ['Gorakhpur', 'Gorakhpur, Uttar Pradesh, India', 26.7605545, 83.3731675],
 ['Jammu-Kashmir', 'Jammu & Kashmir', 33.277839],
 ['Jnarsuguda', 'Jharsuguda, Odisha, India', 21.8554375],
 ['Kamrup', 'Kamrup, Assam, India', 26.3160819],
 ['Karma-bhumi',
  'Q4FH+65P, Shastri Gaon No.1, Assam 782447, India',
  25.7730967],
 ['Kartarpur', 'Kartarpur, Narowal, Punjab, Pakistan', 32.0879424],
 ['Ladakh', 'Ladakh', 34.2268475],
 ['Madurai', 'Madurai, Tamil Nadu, India', 9.9252007],
 ['MahatmaGandhi', '2100-2120 Q St NW, Washington, DC 20008, USA', 38.9110365],
 ['MedTech Zone',
  '2636 Fulton Ave #100, Sacramento, CA 95821, USA',
  38.61411340000001],
 ['Pakyongairport',

In [ ]:
for i in range(0,233):
  coordinates[i] = coordinates[i][:-1]

In [ ]:
plot_data = pd.DataFrame(coordinates, columns=['actual_address', 'formatted_address', 'latitude', 'longitude'])
plot_data.drop_duplicates(subset=['formatted_address'], inplace=True, ignore_index=True)

freqs = list()

for loc in plot_data['formatted_address'].values:
    freqs.append(frequencies[loc])

plot_data.insert(4, "Frequency", freqs, True)
plot_data.to_csv('/content/drive/MyDrive/Lok Sabha Data/Location data/LS16_plot_data.csv')

not_found_locations = list()
for index in notFound:
    not_found_locations.append(locations.iloc[index]['location'])

not_found = pd.DataFrame()
not_found.insert(0, "index", notFound, True)
not_found.insert(1, "location", not_found_locations, True)

not_found.to_csv('/content/drive/MyDrive/Lok Sabha Data/Location data/LS16_not_found.csv')

In [ ]:
geocode_obj[0]['address_components'][0]['short_name']

'GJ'

In [ ]:
len(plot_data)

7052

In [ ]:
plot_data

             actual_address  ... Frequency
0               Maharashtra  ...      1165
1                 Rajasthan  ...       640
2                    States  ...      5673
3     the Union Territories  ...        47
4                 Karnataka  ...      1725
...                     ...  ...       ...
7047                Savitri  ...         1
7048            Sheoraphuli  ...         1
7049           Vaduvoorlake  ...         1
7050           Bailahongala  ...         1
7051              Amendment  ...         1

[7052 rows x 5 columns]

# Working with hindi pos tags

In [2]:
import os
import pandas as pd

In [3]:
files = os.listdir('/content/drive/MyDrive/Lok Sabha Data/Hindi+English POS-NER/16/')

In [4]:
for filename in files:
  index = filename.find('gsheet')
  if index>-1:
    files.remove(filename)

In [5]:
len(files)

274

In [6]:
files = [int(curr[:-12]) for curr in files]

In [7]:
files.sort()

In [11]:
nouns = list()

In [12]:
for filename in files:
  print(f"Working with {filename}")
  data = pd.read_csv(f'/content/drive/MyDrive/Lok Sabha Data/Hindi+English POS-NER/16/{filename}_POS-NER.csv', engine='python')
  data = data[data['word_upos']=='NOUN']
  nouns += list(data['word/entity'])

Working with 1
Working with 2
Working with 3
Working with 4
Working with 5
Working with 6
Working with 7
Working with 8
Working with 9
Working with 10
Working with 11
Working with 12
Working with 13
Working with 14
Working with 15
Working with 16
Working with 17
Working with 18
Working with 19
Working with 20
Working with 21
Working with 22
Working with 23
Working with 24
Working with 25
Working with 26
Working with 27
Working with 28
Working with 29
Working with 30
Working with 31
Working with 32
Working with 33
Working with 34
Working with 35
Working with 36
Working with 37
Working with 38
Working with 39
Working with 40
Working with 41
Working with 42
Working with 43
Working with 44
Working with 45
Working with 46
Working with 47
Working with 48
Working with 49
Working with 50
Working with 51
Working with 52
Working with 53
Working with 54
Working with 55
Working with 56
Working with 57
Working with 58
Working with 59
Working with 60
Working with 61
Working with 62
Working with 63
Working with 64
Working with 65
Working with 66
Working with 67
Working with 68
Working with 69
Working with 70
Working with 71
Working with 72
Working with 73
Working with 74
Working with 75
Working with 76
Working with 77
Working with 78
Working with 79
Working with 80
Working with 82
Working with 83
Working with 84
Working with 85
Working with 86
Working with 87
Working with 88
Working with 89
Working with 90
Working with 91
Working with 92
Working with 93
Working with 94
Working with 95
Working with 96
Working with 97
Working with 98
Working with 99
Working with 100
Working with 102
Working with 103
Working with 104
Working with 105
Working with 106
Working with 107
Working with 108
Working with 109
Working with 110
Working with 111
Working with 112
Working with 113
Working with 114
Working with 115
Working with 116
Working with 117
Working with 118
Working with 119
Working with 120
Working with 121
Working with 122
Working with 123
Working with 124
Working with 125
Working with 126
Working with 127
Working with 128
Working with 129
Working with 131
Working with 132
Working with 133
Working with 134
Working with 135
Working with 136
Working with 137
Working with 138
Working with 139
Working with 140
Working with 141
Working with 142
Working with 143
Working with 144
Working with 145
Working with 146
Working with 147
Working with 148
Working with 149
Working with 150
Working with 151
Working with 152
Working with 153
Working with 154
Working with 155
Working with 156
Working with 157
Working with 158
Working with 159
Working with 160
Working with 161
Working with 162
Working with 163
Working with 164
Working with 165
Working with 166
Working with 167
Working with 168
Working with 169
Working with 170
Working with 171
Working with 172
Working with 173
Working with 175
Working with 176
Working with 177
Working with 178
Working with 179
Working with 180
Working with 220
Working with 221
Working with 222
Working with 223
Working with 224
Working with 225
Working with 226
Working with 227
Working with 228
Working with 229
Working with 230
Working with 231
Working with 232
Working with 233
Working with 234
Working with 235
Working with 236
Working with 237
Working with 238
Working with 239
Working with 240
Working with 241
Working with 242
Working with 243
Working with 244
Working with 246
Working with 247
Working with 248
Working with 250
Working with 251
Working with 252
Working with 253
Working with 254
Working with 255
Working with 256
Working with 257
Working with 258
Working with 259
Working with 260
Working with 261
Working with 262
Working with 263
Working with 264
Working with 265
Working with 266
Working with 267
Working with 268
Working with 269
Working with 270
Working with 271
Working with 272
Working with 273
Working with 274
Working with 275
Working with 276
Working with 277
Working with 278
Working with 279
Working with 280
Working with 281
Working with 282
Working with 283
Working with 284
Working with 285
Working with 286
Working with 287
Working with 288
Working with 289
Working with 290
Working with 291
Working with 292
Working with 293
Working with 294
Working with 295
Working with 296
Working with 297
Working with 298
Working with 299
Working with 300
Working with 302
Working with 303
Working with 304
Working with 305
Working with 306
Working with 307
Working with 308
Working with 309
Working with 310
Working with 311
Working with 312
Working with 313
Working with 314
Working with 315
Working with 316
Working with 317
Working with 318
Working with 319
Working with 320

In [13]:
len(nouns)

1306895

In [ ]:
translated_locations = pd.read_csv('/content/drive/MyDrive/Lok Sabha Data/temp/translatedLocations.csv')

In [ ]:
found = list()

In [ ]:
for index,curr in enumerate(properNouns):
  if curr in list(translated_locations['Hindi']):
    found.append(curr)
  if index%10000==0:
    print(f"{index+1} completed!")

1 completed!
10001 completed!
20001 completed!
30001 completed!
40001 completed!
50001 completed!
60001 completed!
70001 completed!
80001 completed!
90001 completed!
100001 completed!
110001 completed!
120001 completed!
130001 completed!
140001 completed!
150001 completed!
160001 completed!
170001 completed!
180001 completed!
190001 completed!
200001 completed!
210001 completed!
220001 completed!
230001 completed!
240001 completed!
250001 completed!
260001 completed!
270001 completed!
280001 completed!
290001 completed!
300001 completed!
310001 completed!
320001 completed!
330001 completed!
340001 completed!
350001 completed!
360001 completed!
370001 completed!
380001 completed!
390001 completed!
400001 completed!
410001 completed!
420001 completed!
430001 completed!
440001 completed!
450001 completed!
460001 completed!
470001 completed!
480001 completed!
490001 completed!
500001 completed!
510001 completed!
520001 completed!
530001 completed!
540001 completed!
550001 completed!
560001 completed!
570001 completed!
580001 completed!
590001 completed!
600001 completed!
610001 completed!
620001 completed!
630001 completed!
640001 completed!
650001 completed!
660001 completed!
670001 completed!
680001 completed!
690001 completed!
700001 completed!
710001 completed!
720001 completed!
730001 completed!
740001 completed!
750001 completed!
760001 completed!
770001 completed!
780001 completed!
790001 completed!

In [ ]:
found = list(set(found))

In [ ]:
print(len(found))

1205

In [ ]:
print(found)

['बेनी', 'पटना', 'सागर', 'शमसाबाद', 'रोम', 'संगरूर', 'बेलगाम', 'थाईलैंड', 'हैदराबाद', 'कुल्लू', 'रीगा', 'गांधीधाम', 'नगर', 'जयपुर', 'नाभा', 'मुरादाबाद', 'बालाघाट', 'सूडान', 'भिवंडी', 'वारंगल', 'चेतावनी', 'बोडा', 'वेन', 'रायचुर', 'विजयवाड़ा', 'मोरावा', 'बाटा', 'प्रकाश', 'जोरा', 'केलो', 'गुंटूर', 'चाल', 'गोदाम', 'चिली', 'मदुरै', 'धमतरी', 'सिना', 'गंगानगर', 'कानपुर', 'मोनो', 'इटानगर', 'महाराष्ट्र', 'अंजू', 'अशोकनगर', 'माली', 'न्यूजीलैंड', 'जफर', 'बहरीन', 'बिस्मिल', 'दमन', 'जलंधर', 'केंद्रीय', 'जोस', 'मेकॉन', 'परैया', 'वियाना', 'मथुरा', 'सोलन', 'पिंपरी', 'उंझा', 'रूरा', 'चैतन', 'जहानाबाद', 'बरगी', 'करीमगंज', 'सलाम', 'दमोह', 'लन्दन', 'रवांडा', 'वृद्धि', 'नीदरलैंड', 'नाना', 'कांडला', 'नजफ', 'शान', 'नैनीताल', 'अतर', 'फतेहपुर', 'मैहर', 'का', 'मुंगेर', 'राइड', 'नाइजीरिया', 'स्वर्ण', 'कंधार', 'सुरेंद्रनगर', 'मिस्र', 'अहमदनगर', 'भदोही', 'शिकोहाबाद', 'रूस', 'कोहिमा', 'एरिज़ोना', 'पोखरा', 'केन्या', 'लिंकन', 'कमान', 'बंजर', 'मेडन', 'सहरसा', 'मुर्शिदाबाद', 'मोदी', 'कोच्चि', 'घाटी', 'ब्रायन', 'रामटेक', 'डेनमार्क', 'झूला', 'संधि', 'नारा', 'देवास', 'अल्बा', 'तंजानिया', 'हिम्मत', 'पूर्वोत्तर', 'प्रतिभा', 'टोंक', 'फुलेरा', 'राजपुर', 'चिखली', 'बिक्री', 'सुर', 'रतनपुर', 'बहावलपुर', 'जगदीशपुर', 'सिलाई', 'केरल', 'शशि', 'नर', 'कटी', 'नाडियाड', 'संघ', 'वा', 'साइप्रस', 'कलोल', 'उरई', 'जगतसिंहपुर', 'मोगा', 'लीमा', 'अकोट', 'डिंडोरी', 'जाजपुर', 'नवाबगंज', 'बोनी', 'सुपौल', 'बेगूसराय', 'शाहपुरा', 'गीत', 'उदासी', 'जामनगर', 'संदूर', 'सुजगढ़', 'एंटोनी', 'पनामा', 'लाइबेरिया', 'भटिंडा', 'रसायन', 'मोरो', 'बगदाद', 'कथा', 'तमिलनाडु', 'गोवा', 'चितौड़गढ़', 'एडमंड', 'कैर', 'क्रॉसिंग', 'लीबिया', 'मेरठ', 'कोट्टायम', 'मुल्ताई', 'कोनार', 'छतरपुर', 'फोर', 'जैसलमेर', 'बांदीकुई', 'अमरोहा', 'शाहगंज', 'बादामी', 'वैन', 'एल्गिन', 'हो', 'सिमडेगा', 'दिनाजपुर', 'बेल्जियम', 'होजाई', 'पुदुचेरी', 'रायपुर', 'जसीडीह', 'चमन', 'रामा', 'गांधीनगर', 'मंगलौर', 'दिनांक', 'डिब्रूगढ़', 'कविता', 'त्रिपुरा', 'भद्रक', 'चित्तूर', 'गौर', 'सैक्स', 'आइजोल', 'खानपुर', 'निकारागुआ', 'ऑस्ट्रेलिया', 'सोना', 'स्लोवेनिया', 'दादी', 'वियतनाम', 'कोपल', 'चिट्टी', 'सुंदरगढ़', 'पाचोरा', 'घाटमपुर', 'वारी', 'नरसिंहगढ़', 'कुसा', 'बरौली', 'आंवला', 'उत्तराखंड', 'मीरापुर', 'सरहिंद', 'आर्डर', 'अन्वेषण', 'रियाद', 'लाहर', 'तोमर', 'मार', 'संडीला', 'नोहर', 'मगहर', 'खुलना', 'सावा', 'पिलखुआ', 'धर्मनगर', 'इंगलैंड', 'अभय', 'जेतपुर', 'दीमापुर', 'राजगढ़', 'पुष्कर', 'नाथद्वारा', 'तुर्की', 'कास्टिक', 'इजराइल', 'रतनगढ़', 'लाहौर', 'पापुआ', 'दीसा', 'कोचीन', 'गजनी', 'त्रिनिदाद', 'मेनपुरी', 'मालदीव', 'मकराना', 'सोमेश्वर', 'ब्रेस्ट', 'काल्पी', 'दुर्ग', 'लोटा', 'पुलगांव', 'न्यूरो', 'चंदपुर', 'गंभीर', 'कोरम', 'मनोहरपुर', 'मार्केट', 'जमशेदपुर', 'प्रकोप', 'क्लीन', 'झुमरा', 'कोरापुट', 'दिन', 'चंडीगढ़', 'बेन', 'एरियल', 'मोसुल', 'डगलस', 'श्रीरामपुर', 'स्विट्ज़रलैंड', 'पोर्टलैंड', 'जुन्नर', 'अमरेली', 'एम्स', 'चीता', 'मानवता', 'चीर', 'ब्रिस्बेन', 'बुलंदशहर', 'वेनेजुएला', 'एग्री', 'कटक', 'झेलम', 'सहारनपुर', 'नगालैंड', 'मक्सी', 'भरूच', 'पाक', 'मलेशिया', 'अहमदाबाद', 'जगदलपुर', 'पांडिचेरी', 'दरभंगा', 'जलालाबाद', 'मालवन', 'दुर्गापुर', 'चन्दन', 'गोधरा', 'कामा', 'हावर्ड', 'इगतपुरी', 'पूर्ण', 'राजधानी', 'पेशावर', 'कुल्टी', 'खैर', 'नागासाकी', 'गरासिया', 'मारो', 'बहादुरगढ़', 'फिलीपींस', 'चालीसगांव', 'धनबाद', 'जापान', 'भोला', 'बरेली', 'तखतपुर', 'बुलढाणा', 'भवन', 'झारखंड', 'सेवन', 'मडगांव', 'पिट्सबर्ग', 'कैफ', 'धामपुर', 'बंगाल', 'नेल्सन', 'महोबा', 'तिरुचिरापल्ली', 'जलेसर', 'मुदगल', 'मोहम्मद', 'ओरसे', 'श्रीनगर', 'बुधवार', 'बिन', 'पीथमपुर', 'राहुरी', 'चेंजिंग', 'प्रतिबंध', 'साम्राज्य', 'पाटिया', 'चाकन', 'बटला', 'युवा', 'पोखरण', 'मुक्तसर', 'अलीगढ़', 'बिहारीगंज', 'टेरेसा', 'खेड़ा', 'अकबरपुर', 'धार', 'अर्थ', 'जवार', 'मेदिनीपुर', 'ताइचुंग', 'बोरीवली', 'मध्य', 'मधुबनी', 'शिवगंगा', 'डीडवाना', 'पुरवा', 'बारा', 'एलेन', 'बिग', 'हजारीबाग', 'माई', 'कपड़ा', 'अमलनेर', 'काबुल', 'रामगुंडम', 'टीला', 'जलालपुर', 'कोटपुतली', 'दुमका', 'बोर्न', 'उपवन', 'नंदुरबार', 'मेट्रो', 'फिनलैंड', 'रीवा', 'मनियार', 'मलावी', 'पोर्ट', 'बस्ती', 'खैरागढ़', 'वर्धा', 'श्योपुर', 'पूल', 'पीआईओ', 'भिंड', 'मधुपुर', 'भजन', 'मुस्तफाबाद', 'पनवेल', 'कैम्पा', 'छावनी', 'कनाडा', 'कोसम्बा', 'उर', 'मुंबई', 'अंकलेश्वर', 'राजसमंद', 'सरदारशहर', 'हैती', 'विरार', 'चेम्सफोर्ड', 'बंगा', 'उत्तरी', 'मोरबी', 'इटली', 'देवता', 'चुरू', 'देवरिया', 'सावन', 'जीरो', 'ताशकंद', 'तालचेर', 'रामगढ़', 'अंबाला', 'हाइड', 'फरक्का', 'कुक्षी', 'लिंग', 'फैसलाबाद', 'मोरक्को', 'बर्न', 'व्लादिमीर', 'रावलपिंडी', 'इंडियाना', 'इलाहाबाद', 'राजुला', 'सीरिया', 'पंढरपुर', 'तिरुपति', 'कोलंबस', 'सलेम', 'खेल', 'मुंगेली', 'कृष्णागिरी', 'तिनसुकिया', 'रानाघाट', 'भिलाई', 'रांची', 'स्वतंत्रता', 'एडीए', 'करणपुर', 'झारसुगुडा', 'क्योटो', 'विदिशा', 'डूंगरपुर', 'कोलकाता', 'चक्रधरपुर', 'पठानकोट', 'दुकानदार', 'रनिंग', 'बूंदी', 'जलगांव', 'कैथल', 'मुरैना', 'बासर', 'धौलपुर', 'शिरडी', 'कोरबा', 'बांसवाड़ा', 'शताब्दी', 'कोयंबटूर', 'अंबा', 'निबंधन', 'मणिपुर', 'गुलबर्गा', 'वेरावल', 'अल्मा', 'ओमान', 'केंट', 'रामेश्वरम', 'पश्चिम', 'शेयर', 'सैंट', 'मैरवा', 'हेड', 'नांदेड़', 'पोरबंदर', 'काल', 'ठाकुरद्वारा', 'अनंतपुर', 'टोक्यो', 'बुकानन', 'मोहाली', 'खड़गपुर', 'ओबामा', 'जतारा', 'खंभा', 'सोमालिया', 'सोमवार', 'ग्वालियर', 'भूरा', 'वेयर', 'अजमेर', 'यवतमाल', 'मेहर', 'भान', 'कल्याणी', 'कोडो', 'टोल', 'यात्री', 'मैथ्यू', 'इंडोनेशिया', 'अलवर', 'इस्लामाबाद', 'भुवनेश्वर', 'धारी', 'पूर्व', 'शिमला', 'खुर्दा', 'डाल्टनगंज', 'मलीहाबाद', 'संबलपुर', 'बन्दा', 'सिरसा', 'हवाई', 'रत्नागिरि', 'क्रोएशिया', 'औरंगाबाद', 'लंदन', 'यूक्रेन', 'मार्टिन', 'लोअर', 'नोखा', 'रोमन', 'बिलग्राम', 'बीजापुर', 'सीधी', 'माला', 'टाटा', 'मंडी', 'अकोला', 'कन्नौज', 'अबू', 'दाहोद', 'छापर', 'टेनी', 'हंडिया', 'कमल', 'मेला', 'अमृतसर', 'अन्ना', 'बूम', 'ओरिएंटल', 'लक्सर', 'मैसूर', 'बहादुरगंज', 'टर्म', 'मेक्सिको', 'रानी', 'नलगोंडा', 'बुटवल', 'नेपालगंज', 'नागदा', 'खजुराहो', 'मिशेल', 'चिरांग', 'पेरिस', 'साक्षी', 'नाका', 'काकोरी', 'सिंगूर', 'मल्कापुर', 'हरा', 'पेरू', 'टोयोटा', 'हिम्मतनगर', 'कटिहार', 'रेनी', 'ऊना', 'इंदौर', 'तारकेश्वर', 'नानपारा', 'अंगोल', 'अहमदपुर', 'पद्म', 'फूलपुर', 'वरोरा', 'नसीराबाद', 'बदलापुर', 'मंडपम', 'पीसा', 'इथियोपिया', 'मटेरा', 'काला', 'मोरी', 'जावरा', 'जौनपुर', 'गति', 'नील', 'परिसर', 'अजनाला', 'तेलंगाना', 'सिकंदराबाद', 'बढ़ई', 'दौसा', 'डोंट', 'दादू', 'लोदी', 'बेल्लारी', 'रिगा', 'सिक्किम', 'संघीय', 'सरदार', 'शेखपुरा', 'वाराणसी', 'देवा', 'जायदाद', 'देवगढ़', 'कर्नाटक', 'आद्रा', 'बिसलपुर', 'मोबाइल', 'कांड', 'कर्जत', 'अकु', 'जयनगर', 'शिलांग', 'बिंदकी', 'घोसी', 'लैब', 'पेन', 'ओखा', 'वनी', 'खन्ना', 'हिसार', 'जाम्बिया', 'धुरी', 'जेना', 'वेस्टर्न', 'बेग', 'गोलाघाट', 'मर्सी', 'छत्तीसगढ', 'असम', 'पुलिस', 'मोती', 'हरियाणा', 'मार्च', 'फिरोजपुर', 'मोरार', 'हमार', 'बाइस', 'गोहाना', 'बेला', 'दोहा', 'टैंक', 'कोप्पल', 'बहस', 'मैनचेस्टर', 'गंगटोक', 'मंडन', 'दीव', 'चितरंजन', 'झील', 'इचलकरंजी', 'काका', 'थीम', 'नेल्लोर', 'हेलसिंकी', 'टेनरी', 'वेसेल', 'वुहान', 'मुरलीगंज', 'राजपुरा', 'सेलु', 'वजीराबाद', 'बाई', 'भवानीपुर', 'चिकमंगलूर', 'रावेर', 'पंजाब', 'रोटा', 'रॉय', 'जबलपुर', 'पूर्णिया', 'कतर', 'नूरपुर', 'नासिक', 'सिल्वासा', 'जोरहाट', 'रनिया', 'हसनपुर', 'महाड', 'राय', 'भारत', 'ईरान', 'मंडल', 'गुना', 'शाहाबाद', 'विश्वविद्यालय', 'लाओस', 'सेशल्स', 'बांका', 'वारसा', 'बिलासपुर', 'होंडा', 'मुहम्मदाबाद', 'सादरी', 'बसरा', 'औसा', 'टिंडीवनम', 'चौक', 'रामपुर', 'शेरपुर', 'लोनी', 'प्लेटो', 'चेरिया', 'केंद्र', 'धनेरा', 'पाकिस्तान', 'बाढ़', 'आश्रम', 'बाड़मेर', 'ईसाई', 'उमरिया', 'सेंस', 'स्पेयर', 'हरिद्वार', 'राई', 'सीमा', 'गिद्ध', 'टेटे', 'शिकागो', 'उदयपुर', 'झाबुआ', 'रामनगर', 'तह', 'खोपोली', 'वेल्लोर', 'फोर्ड', 'मनाली', 'पिलर', 'देवबंद', 'दीनापुर', 'गढ़वा', 'आसन', 'सोम', 'हिंगोली', 'गोमो', 'जम्मू', 'नेपल्स', 'कल्याण', 'टिहरी', 'शिवपुरी', 'कोल्हापुर', 'निजामाबाद', 'शिमोगा', 'श्रद्धा', 'प्रशांत', 'कोलार', 'माचेरला', 'लेवल', 'हसन', 'जीनिंग', 'सिरी', 'गुजरात', 'रायबरेली', 'पवई', 'इस्लामपुर', 'तिलहर', 'जिनेवा', 'द', 'आलंदी', 'शांतिपुर', 'नाग', 'उद्यम', 'उस्मानाबाद', 'पोलैंड', 'बसवा', 'कंडी', 'जूनागढ़', 'जीन', 'ईडी', 'कोलंबिया', 'मोजाम्बिक', 'मैदान', 'सुल्तानपुर', 'कैम्पोस', 'वनस्पति', 'वडनगर', 'गंज', 'कीरतपुर', 'गया', 'रायसेन', 'चिदंबरम', 'आयरलैंड', 'विहारी', 'सूबेदार', 'येवला', 'भिवानी', 'छलनी', 'बोकारो', 'अबी', 'श्रीगोंदा', 'लखनऊ', 'एरंडोल', 'लागोस', 'गुमला', 'टांडा', 'बंदर', 'गुलाबपुरा', 'कांकेर', 'सूरीनाम', 'करिया', 'रघुनाथपुर', 'सिएटल', 'प्रतापगढ़', 'बारपेटा', 'शाही', 'जोगबनी', 'खलीलाबाद', 'भगवान', 'अल्बानिया', 'डेल्टा', 'कोकराझार', 'गंगोह', 'सज्जन', 'बीजिंग', 'बाजार', 'एशिया', 'लातूर', 'शिवहर', 'टायर', 'समाज', 'बीमा', 'उधमपुर', 'विल', 'बारह', 'मकाऊ', 'खंडवा', 'ऋषि', 'कैरी', 'गोरखपुर', 'जमालपुर', 'तारानगर', 'संविधान', 'क्यूबा', 'कैमरून', 'लोनर', 'जलाशय', 'गठबंधन', 'हुड', 'स्पेन', 'छातापुर', 'जन्म', 'सिरोही', 'नीम', 'आनंदपुर', 'मधुमक्खी', 'लातेहार', 'बाँदा', 'लखीमपुर', 'लीड', 'धर्मपुर', 'वर्ड', 'दादर', 'वाशिंगटन', 'माया', 'चारा', 'बेतिया', 'हुबली', 'पिपराइच', 'ताल', 'लो', 'रोहा', 'गीता', 'अमरनाथ', 'कटघोरा', 'चीन', 'मेडक', 'गोपालगंज', 'कोलंबो', 'विशाखापत्तनम', 'हल्दिया', 'शंघाई', 'आनंद', 'जनकपुर', 'सियालकोट', 'पुणे', 'सिंध', 'शिवकाशी', 'काया', 'नीवा', 'ताइवान', 'डेहरी', 'विक्टोरिया', 'अचलपुर', 'कंबोडिया', 'म्यांमार', 'चंदेरी', 'रायगढ़', 'मेनन', 'राइज़', 'आदमपुर', 'काई', 'बाली', 'इक्वेडोर', 'तिजारा', 'कोझिकोड', 'अदन', 'दाखला', 'अटलांटा', 'तलवार', 'बिहार', 'कश्मीर', 'अगरतला', 'चंबा', 'वडोदरा', 'सतना', 'रोमानिया', 'तेजपुर', 'नीच', 'अनुपपुर', 'राजकोट', 'तारा', 'सिवान', 'महेश्वर', 'बैरी', 'किशनगंज', 'जसपुर', 'मोरेनी', 'ऊन', 'गंगापुर', 'अनूपशहर', 'चेन्नई', 'मैडिसन', 'अमली', 'नवा', 'रन', 'रुड़की', 'यमन', 'घाटशिला', 'प्लेस', 'प्रिजन', 'एक्सम', 'हिलसा', 'अर्चना', 'कोसी', 'कोंडागांव', 'वेलूर', 'भूमि', 'कबाला', 'हडसन', 'वेलकम', 'सीहोर', 'मुजफ्फरनगर', 'लीज', 'फ्रांस', 'वीर', 'ब्यावरा', 'खोवाई', 'सिलचर', 'भोपाल', 'पेट्रो', 'रेटिंग', 'गान', 'बोडो', 'जंगीपुर', 'भवानी', 'वेल', 'ढाका', 'पैरा', 'किशनगढ़', 'बच्चन', 'वृक्षारोपण', 'यमुनानगर', 'साकी', 'भंडारा', 'दक्षिण', 'रो', 'अंग', 'सिलीगुड़ी', 'जरवल', 'बोल्डर', 'इराक', 'राजमपेट', 'मातरम्', 'कैली', 'बेरी', 'अलीगंज', 'अलास्का', 'इट', 'किरण', 'विविध', 'हमी', 'हरसुद', 'स्थिरता', 'मास्को', 'सरदारगढ़', 'नागपुर', 'ताजपुर', 'कोराच', 'पोर्टल', 'जहाजपुर', 'मिजोरम', 'बारासात', 'शेरघाटी', 'मिल्टन', 'भरथना', 'मंगला', 'सर्वोच्च', 'आरा', 'एथलीट', 'ऑस्टिन', 'जाफना', 'रोहतक', 'वेस्ट', 'मसूरी', 'बंकुरा', 'तुलसीपुर', 'बख्तियारपुर', 'शाहपुर', 'बांग्लादेश', 'शेरवुड', 'तेहरान', 'भुज', 'स्वास्थ', 'गोवर्धन', 'पुरुलिया', 'हंगरी', 'मक्का', 'भूटान', 'अन्न', 'भागलपुर', 'व्यास', 'इंफाल', 'परभनी', 'रेती', 'संभल', 'मिलक', 'नोएडा', 'एंडरसन', 'अंगोला', 'कारण', 'स्वीडन', 'लेह', 'लुगू', 'काशीपुर', 'ओबी', 'टाल', 'पन्ना', 'डलास', 'छोटा', 'गोंडल', 'मंच', 'पाली', 'रेन', 'कोटा', 'पुर्तगाल', 'बारामुला', 'बक्सर', 'गुनुपुर', 'अमरपुर', 'अध्ययन', 'मुंद्रा', 'मन', 'दलाई', 'मर्सिडीज', 'तुलसी', 'बरनाला', 'हिरोशिमा', 'बुरहानपुर', 'देखो', 'भटकल', 'बिजनौर', 'मुजफ्फराबाद', 'जशपुर', 'ऋषिकेश', 'उज्जैन', 'हवेली', 'मासी', 'अवतार', 'कलम', 'जॉर्ज', 'पुरी', 'चटगांव', 'बैंकाक', 'खामगांव', 'ओडिशा', 'काठमांडू', 'सरखेज', 'शेगाव', 'आशा', 'विनीत', 'गुवाहाटी', 'शाहजहांपुर', 'तिरुवनंतपुरम', 'कडप्पा', 'काली', 'धुबरी', 'निर्मल', 'लोनावाला', 'सैन', 'रामनाथपुरम', 'कारवार', 'अमरावती', 'रेवती', 'होशंगाबाद', 'निवाई', 'भावनगर', 'घाना', 'कुआंतन', 'डोडा', 'हट्टा', 'वेल्स', 'सो', 'सांबा', 'तुर्कमेनिस्तान', 'लेबनान', 'सिंगापुर', 'देहात', 'कोपरगांव', 'शिंजो', 'नैशनल', 'लाला', 'नेपाल', 'बाबू', 'मेघालय', 'छत्रपुर', 'हावेरी', 'मो', 'आजमगढ़', 'महबूबनगर', 'बोलपुर', 'पापा', 'रामगंज', 'सिडनी', 'वाई', 'बेस्ट', 'सोजत', 'तानसेन', 'कोको', 'मुजफ्फरपुर', 'राइट', 'जवाहर', 'डिंडीगुल', 'पालिताना', 'किराया', 'ल्हासा', 'निःशुल्क', 'हनुमानगढ़', 'जुमा', 'कर्नलगंज', 'प्राचीन', 'एल्स्ट', 'कोबे', 'नागा', 'कोंच', 'नैनपुर', 'पुलवामा', 'भाद्रा', 'ठाकुरगंज', 'करीमनगर', 'पलवल', 'रिक्त', 'हुगली', 'चरखारी', 'होप', 'भरतपुर', 'चन्द्र', 'नेजो', 'झज्जर', 'अनंतनाग', 'बोटाद', 'धुलिया', 'समर', 'गंगारामपुर', 'कुंदा', 'करूर', 'सुनाम', 'लुधियाना', 'रोशन', 'नारायणा', 'नजीबाबाद', 'वेस्टलैंड', 'पारी', 'बेंगलुरु', 'जोधपुर', 'कराची', 'अमेरिका', 'रामपुरा', 'फ़िजी', 'सभा', 'वापी', 'जर्मनी', 'दुबई', 'दिल्ली', 'कस्बा', 'पट्टी']

In [ ]:
textfile = open("/content/drive/MyDrive/Lok Sabha Data/temp/hindiLocations.txt", "w")
for element in found:
    textfile.write(element + "\n")
textfile.close()

In [ ]:
my_file = open("/content/drive/MyDrive/Lok Sabha Data/temp/hindiLocations.txt", "r", encoding="utf8")
content = my_file.read()
my_file.close()

locations_in_hindi = content.split('\n')

locations_in_hindi = locations_in_hindi[:-1]

In [ ]:
pip install googlemaps

Collecting googlemaps
  Downloading googlemaps-4.5.3.tar.gz (32 kB)
Requirement already satisfied: requests<3.0,>=2.20.0 in /usr/local/lib/python3.7/dist-packages (from googlemaps) (2.23.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (2021.10.8)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (1.24.3)
Building wheels for collected packages: googlemaps
  Building wheel for googlemaps (setup.py) ... done
  Created wheel for googlemaps: filename=googlemaps-4.5.3-py3-none-any.whl size=38479 sha256=32e35c180afb5229efcdcd763450109f68bb43bcc7a3129e51f813625fddf041
  Stored in directory: /root/.cache/pip/wheels/fa/1a/1c/cc0b8a1652a3f06aea586b0e4714a81bafed830513969baf92
Successfully built googlemaps
Installing collected packages: googlemaps
Successfully installed googlemaps-4.5.3

In [ ]:
import time
import googlemaps
import pandas as pd

In [ ]:
g_API = "AIzaSyCAB5jV41tYYmPdndd0MDihFE5sK-tB8NA"
gmaps_key = googlemaps.Client(key=g_API)

In [ ]:
coordinates = list()
notFound = list()

In [ ]:
start_time = time.time()

In [ ]:
for index,loc in enumerate(locations_in_hindi):
  response = gmaps_key.geocode(loc)
  if len(response)>0:
    print(index, "found")
    coordinates.append([loc, response[0]['formatted_address'], response[0]['geometry']['location']['lat'], response[0]['geometry']['location']['lng']])
  
  else:
    notFound.append(index)
    print(index, "not found")
  print(f"Total : {index+1-len(notFound)}/{index+1}")
  print("Time elapsed :", time.time()-start_time)
  print("\n----------------------------------\n")

Streaming output truncated to the last 5000 lines.
----------------------------------

372 found
Total : 373/373
Time elapsed : 167.3483111858368

----------------------------------

373 found
Total : 374/374
Time elapsed : 167.74031043052673

----------------------------------

374 found
Total : 375/375
Time elapsed : 168.24473690986633

----------------------------------

375 found
Total : 376/376
Time elapsed : 168.5384635925293

----------------------------------

376 found
Total : 377/377
Time elapsed : 168.97007584571838

----------------------------------

377 found
Total : 378/378
Time elapsed : 169.38336849212646

----------------------------------

378 found
Total : 379/379
Time elapsed : 169.68090152740479

----------------------------------

379 found
Total : 380/380
Time elapsed : 169.92578601837158

----------------------------------

380 found
Total : 381/381
Time elapsed : 170.43945217132568

----------------------------------

381 found
Total : 382/382
Time elapsed : 170.8530457019806

----------------------------------

382 found
Total : 383/383
Time elapsed : 171.13733768463135

----------------------------------

383 found
Total : 384/384
Time elapsed : 171.42560935020447

----------------------------------

384 found
Total : 385/385
Time elapsed : 171.7181260585785

----------------------------------

385 found
Total : 386/386
Time elapsed : 172.32209086418152

----------------------------------

386 found
Total : 387/387
Time elapsed : 172.7396821975708

----------------------------------

387 found
Total : 388/388
Time elapsed : 173.21024203300476

----------------------------------

388 found
Total : 389/389
Time elapsed : 173.67862820625305

----------------------------------

389 found
Total : 390/390
Time elapsed : 173.9554316997528

----------------------------------

390 found
Total : 391/391
Time elapsed : 174.33052706718445

----------------------------------

391 found
Total : 392/392
Time elapsed : 174.75797605514526

----------------------------------

392 found
Total : 393/393
Time elapsed : 175.09752488136292

----------------------------------

393 found
Total : 394/394
Time elapsed : 175.55053687095642

----------------------------------

394 found
Total : 395/395
Time elapsed : 175.99553298950195

----------------------------------

395 found
Total : 396/396
Time elapsed : 176.28585743904114

----------------------------------

396 found
Total : 397/397
Time elapsed : 176.700115442276

----------------------------------

397 found
Total : 398/398
Time elapsed : 177.12046194076538

----------------------------------

398 found
Total : 399/399
Time elapsed : 177.54345512390137

----------------------------------

399 found
Total : 400/400
Time elapsed : 178.08831071853638

----------------------------------

400 found
Total : 401/401
Time elapsed : 178.36943674087524

----------------------------------

401 found
Total : 402/402
Time elapsed : 178.7526490688324

----------------------------------

402 found
Total : 403/403
Time elapsed : 179.22923684120178

----------------------------------

403 found
Total : 404/404
Time elapsed : 179.66148948669434

----------------------------------

404 found
Total : 405/405
Time elapsed : 180.06958746910095

----------------------------------

405 found
Total : 406/406
Time elapsed : 180.52329230308533

----------------------------------

406 found
Total : 407/407
Time elapsed : 180.97260236740112

----------------------------------

407 found
Total : 408/408
Time elapsed : 181.31964135169983

----------------------------------

408 found
Total : 409/409
Time elapsed : 181.74613881111145

----------------------------------

409 found
Total : 410/410
Time elapsed : 182.15906524658203

----------------------------------

410 found
Total : 411/411
Time elapsed : 182.6123878955841

----------------------------------

411 found
Total : 412/412
Time elapsed : 182.9139895439148

----------------------------------

412 found
Total : 413/413
Time elapsed : 183.33063864707947

----------------------------------

413 found
Total : 414/414
Time elapsed : 183.59599828720093

----------------------------------

414 found
Total : 415/415
Time elapsed : 183.8805696964264

----------------------------------

415 found
Total : 416/416
Time elapsed : 184.29552173614502

----------------------------------

416 found
Total : 417/417
Time elapsed : 184.8061716556549

----------------------------------

417 found
Total : 418/418
Time elapsed : 185.30668449401855

----------------------------------

418 found
Total : 419/419
Time elapsed : 185.81282329559326

----------------------------------

419 found
Total : 420/420
Time elapsed : 186.10837769508362

----------------------------------

420 found
Total : 421/421
Time elapsed : 186.41476726531982

----------------------------------

421 found
Total : 422/422
Time elapsed : 186.8021855354309

----------------------------------

422 found
Total : 423/423
Time elapsed : 187.17674136161804

----------------------------------

423 found
Total : 424/424
Time elapsed : 187.52887320518494

----------------------------------

424 found
Total : 425/425
Time elapsed : 188.0101706981659

----------------------------------

425 found
Total : 426/426
Time elapsed : 188.4538631439209

----------------------------------

426 found
Total : 427/427
Time elapsed : 188.69654202461243

----------------------------------

427 found
Total : 428/428
Time elapsed : 188.9555094242096

----------------------------------

428 found
Total : 429/429
Time elapsed : 189.42088508605957

----------------------------------

429 found
Total : 430/430
Time elapsed : 189.88258743286133

----------------------------------

430 found
Total : 431/431
Time elapsed : 190.41462922096252

----------------------------------

431 found
Total : 432/432
Time elapsed : 190.70420289039612

----------------------------------

432 found
Total : 433/433
Time elapsed : 191.00794219970703

----------------------------------

433 found
Total : 434/434
Time elapsed : 191.3882703781128

----------------------------------

434 found
Total : 435/435
Time elapsed : 191.85228967666626

----------------------------------

435 found
Total : 436/436
Time elapsed : 192.1834146976471

----------------------------------

436 found
Total : 437/437
Time elapsed : 192.68638014793396

----------------------------------

437 found
Total : 438/438
Time elapsed : 193.11187839508057

----------------------------------

438 found
Total : 439/439
Time elapsed : 193.37507224082947

----------------------------------

439 found
Total : 440/440
Time elapsed : 193.80673789978027

----------------------------------

440 found
Total : 441/441
Time elapsed : 194.49929356575012

----------------------------------

441 found
Total : 442/442
Time elapsed : 194.91094207763672

----------------------------------

442 found
Total : 443/443
Time elapsed : 195.22255206108093

----------------------------------

443 found
Total : 444/444
Time elapsed : 195.47923755645752

----------------------------------

444 found
Total : 445/445
Time elapsed : 195.88150000572205

----------------------------------

445 found
Total : 446/446
Time elapsed : 196.35274291038513

----------------------------------

446 found
Total : 447/447
Time elapsed : 196.86005425453186

----------------------------------

447 found
Total : 448/448
Time elapsed : 197.31176376342773

----------------------------------

448 found
Total : 449/449
Time elapsed : 197.73829674720764

----------------------------------

449 found
Total : 450/450
Time elapsed : 198.25140237808228

----------------------------------

450 found
Total : 451/451
Time elapsed : 198.70213723182678

----------------------------------

451 found
Total : 452/452
Time elapsed : 199.18632817268372

----------------------------------

452 found
Total : 453/453
Time elapsed : 199.4974925518036

----------------------------------

453 found
Total : 454/454
Time elapsed : 200.09470057487488

----------------------------------

454 found
Total : 455/455
Time elapsed : 200.55238580703735

----------------------------------

455 found
Total : 456/456
Time elapsed : 201.30422043800354

----------------------------------

456 found
Total : 457/457
Time elapsed : 202.0199453830719

----------------------------------

457 found
Total : 458/458
Time elapsed : 202.56153750419617

----------------------------------

458 found
Total : 459/459
Time elapsed : 202.82880544662476

----------------------------------

459 found
Total : 460/460
Time elapsed : 203.11291980743408

----------------------------------

460 found
Total : 461/461
Time elapsed : 203.35804724693298

----------------------------------

461 found
Total : 462/462
Time elapsed : 203.62956047058105

----------------------------------

462 found
Total : 463/463
Time elapsed : 203.89268922805786

----------------------------------

463 found
Total : 464/464
Time elapsed : 204.16950297355652

----------------------------------

464 found
Total : 465/465
Time elapsed : 204.61800813674927

----------------------------------

465 found
Total : 466/466
Time elapsed : 205.03751301765442

----------------------------------

466 found
Total : 467/467
Time elapsed : 205.44895601272583

----------------------------------

467 found
Total : 468/468
Time elapsed : 205.93096709251404

----------------------------------

468 found
Total : 469/469
Time elapsed : 206.20249700546265

----------------------------------

469 found
Total : 470/470
Time elapsed : 206.46320700645447

----------------------------------

470 found
Total : 471/471
Time elapsed : 206.8543884754181

----------------------------------

471 found
Total : 472/472
Time elapsed : 207.13952445983887

----------------------------------

472 found
Total : 473/473
Time elapsed : 207.43015003204346

----------------------------------

473 found
Total : 474/474
Time elapsed : 207.70389914512634

----------------------------------

474 found
Total : 475/475
Time elapsed : 208.1352744102478

----------------------------------

475 found
Total : 476/476
Time elapsed : 208.5653989315033

----------------------------------

476 found
Total : 477/477
Time elapsed : 209.04062724113464

----------------------------------

477 found
Total : 478/478
Time elapsed : 209.63605785369873

----------------------------------

478 found
Total : 479/479
Time elapsed : 210.01875615119934

----------------------------------

479 found
Total : 480/480
Time elapsed : 210.27451634407043

----------------------------------

480 found
Total : 481/481
Time elapsed : 210.50699400901794

----------------------------------

481 found
Total : 482/482
Time elapsed : 210.75371193885803

----------------------------------

482 found
Total : 483/483
Time elapsed : 211.20798802375793

----------------------------------

483 found
Total : 484/484
Time elapsed : 211.46240901947021

----------------------------------

484 found
Total : 485/485
Time elapsed : 211.9007444381714

----------------------------------

485 found
Total : 486/486
Time elapsed : 212.17724800109863

----------------------------------

486 found
Total : 487/487
Time elapsed : 212.66012358665466

----------------------------------

487 found
Total : 488/488
Time elapsed : 213.0837116241455

----------------------------------

488 found
Total : 489/489
Time elapsed : 213.5251181125641

----------------------------------

489 found
Total : 490/490
Time elapsed : 213.92015600204468

----------------------------------

490 found
Total : 491/491
Time elapsed : 214.33316826820374

----------------------------------

491 found
Total : 492/492
Time elapsed : 214.7548005580902

----------------------------------

492 found
Total : 493/493
Time elapsed : 215.1697874069214

----------------------------------

493 found
Total : 494/494
Time elapsed : 215.69059705734253

----------------------------------

494 found
Total : 495/495
Time elapsed : 215.99421906471252

----------------------------------

495 found
Total : 496/496
Time elapsed : 216.4739670753479

----------------------------------

496 found
Total : 497/497
Time elapsed : 216.88954877853394

----------------------------------

497 found
Total : 498/498
Time elapsed : 217.37958884239197

----------------------------------

498 found
Total : 499/499
Time elapsed : 217.78276586532593

----------------------------------

499 found
Total : 500/500
Time elapsed : 218.18546795845032

----------------------------------

500 found
Total : 501/501
Time elapsed : 218.57032108306885

----------------------------------

501 found
Total : 502/502
Time elapsed : 218.8213849067688

----------------------------------

502 found
Total : 503/503
Time elapsed : 219.20612359046936

----------------------------------

503 found
Total : 504/504
Time elapsed : 219.50417256355286

----------------------------------

504 found
Total : 505/505
Time elapsed : 219.84289169311523

----------------------------------

505 found
Total : 506/506
Time elapsed : 220.19219613075256

----------------------------------

506 found
Total : 507/507
Time elapsed : 220.60198211669922

----------------------------------

507 found
Total : 508/508
Time elapsed : 221.08389735221863

----------------------------------

508 found
Total : 509/509
Time elapsed : 221.40409874916077

----------------------------------

509 found
Total : 510/510
Time elapsed : 221.76608777046204

----------------------------------

510 found
Total : 511/511
Time elapsed : 222.20477867126465

----------------------------------

511 found
Total : 512/512
Time elapsed : 222.65302205085754

----------------------------------

512 found
Total : 513/513
Time elapsed : 223.0930826663971

----------------------------------

513 found
Total : 514/514
Time elapsed : 223.5021378993988

----------------------------------

514 found
Total : 515/515
Time elapsed : 223.95248126983643

----------------------------------

515 found
Total : 516/516
Time elapsed : 224.34841585159302

----------------------------------

516 found
Total : 517/517
Time elapsed : 224.758850812912

----------------------------------

517 found
Total : 518/518
Time elapsed : 225.01088070869446

----------------------------------

518 found
Total : 519/519
Time elapsed : 225.30299615859985

----------------------------------

519 found
Total : 520/520
Time elapsed : 225.57047414779663

----------------------------------

520 found
Total : 521/521
Time elapsed : 225.81541538238525

----------------------------------

521 found
Total : 522/522
Time elapsed : 226.24954628944397

----------------------------------

522 found
Total : 523/523
Time elapsed : 226.66538262367249

----------------------------------

523 found
Total : 524/524
Time elapsed : 227.09990763664246

----------------------------------

524 found
Total : 525/525
Time elapsed : 227.50444531440735

----------------------------------

525 found
Total : 526/526
Time elapsed : 227.77861881256104

----------------------------------

526 found
Total : 527/527
Time elapsed : 228.3472020626068

----------------------------------

527 found
Total : 528/528
Time elapsed : 228.58468461036682

----------------------------------

528 found
Total : 529/529
Time elapsed : 229.07478380203247

----------------------------------

529 found
Total : 530/530
Time elapsed : 229.37548542022705

----------------------------------

530 found
Total : 531/531
Time elapsed : 229.83925819396973

----------------------------------

531 found
Total : 532/532
Time elapsed : 230.2672245502472

----------------------------------

532 found
Total : 533/533
Time elapsed : 230.60318517684937

----------------------------------

533 found
Total : 534/534
Time elapsed : 230.86179971694946

----------------------------------

534 found
Total : 535/535
Time elapsed : 231.10724329948425

----------------------------------

535 found
Total : 536/536
Time elapsed : 231.38511610031128

----------------------------------

536 found
Total : 537/537
Time elapsed : 231.80085706710815

----------------------------------

537 found
Total : 538/538
Time elapsed : 232.19022941589355

----------------------------------

538 found
Total : 539/539
Time elapsed : 232.44269061088562

----------------------------------

539 found
Total : 540/540
Time elapsed : 232.8631660938263

----------------------------------

540 found
Total : 541/541
Time elapsed : 233.14722895622253

----------------------------------

541 found
Total : 542/542
Time elapsed : 233.61077857017517

----------------------------------

542 found
Total : 543/543
Time elapsed : 234.03960514068604

----------------------------------

543 found
Total : 544/544
Time elapsed : 234.45147800445557

----------------------------------

544 found
Total : 545/545
Time elapsed : 234.89511275291443

----------------------------------

545 found
Total : 546/546
Time elapsed : 235.35265183448792

----------------------------------

546 found
Total : 547/547
Time elapsed : 235.62040996551514

----------------------------------

547 found
Total : 548/548
Time elapsed : 235.93876934051514

----------------------------------

548 found
Total : 549/549
Time elapsed : 236.34259676933289

----------------------------------

549 found
Total : 550/550
Time elapsed : 236.7502989768982

----------------------------------

550 found
Total : 551/551
Time elapsed : 236.9969437122345

----------------------------------

551 found
Total : 552/552
Time elapsed : 237.54830861091614

----------------------------------

552 found
Total : 553/553
Time elapsed : 238.00296568870544

----------------------------------

553 found
Total : 554/554
Time elapsed : 238.4568943977356

----------------------------------

554 found
Total : 555/555
Time elapsed : 238.89124727249146

----------------------------------

555 found
Total : 556/556
Time elapsed : 239.18413376808167

----------------------------------

556 found
Total : 557/557
Time elapsed : 239.59411072731018

----------------------------------

557 found
Total : 558/558
Time elapsed : 240.01438546180725

----------------------------------

558 found
Total : 559/559
Time elapsed : 240.41957211494446

----------------------------------

559 found
Total : 560/560
Time elapsed : 240.70115303993225

----------------------------------

560 found
Total : 561/561
Time elapsed : 240.983412027359

----------------------------------

561 found
Total : 562/562
Time elapsed : 241.22151732444763

----------------------------------

562 found
Total : 563/563
Time elapsed : 241.79380345344543

----------------------------------

563 found
Total : 564/564
Time elapsed : 242.11895275115967

----------------------------------

564 found
Total : 565/565
Time elapsed : 242.582111120224

----------------------------------

565 found
Total : 566/566
Time elapsed : 243.15642285346985

----------------------------------

566 found
Total : 567/567
Time elapsed : 243.40067863464355

----------------------------------

567 found
Total : 568/568
Time elapsed : 243.82353973388672

----------------------------------

568 found
Total : 569/569
Time elapsed : 244.0846643447876

----------------------------------

569 found
Total : 570/570
Time elapsed : 244.50116777420044

----------------------------------

570 found
Total : 571/571
Time elapsed : 244.8929579257965

----------------------------------

571 found
Total : 572/572
Time elapsed : 245.29309678077698

----------------------------------

572 found
Total : 573/573
Time elapsed : 245.717613697052

----------------------------------

573 found
Total : 574/574
Time elapsed : 246.26105070114136

----------------------------------

574 found
Total : 575/575
Time elapsed : 246.71342253684998

----------------------------------

575 found
Total : 576/576
Time elapsed : 246.9778459072113

----------------------------------

576 found
Total : 577/577
Time elapsed : 247.23848581314087

----------------------------------

577 found
Total : 578/578
Time elapsed : 247.6365737915039


In [ ]:
coordinates[1]

['पटना', 'Patna, Bihar, India', 25.5940947, 85.1375645]

In [ ]:
hindi_coordinates = pd.DataFrame(coordinates, columns=['actual_address', 'formatted_address', 'latitude', 'longitude'])
hindi_coordinates.drop_duplicates(subset=['formatted_address'], inplace=True, ignore_index=True)

In [ ]:
len(hindi_coordinates)

1188

In [ ]:
english_coordinates = pd.read_csv('/content/drive/MyDrive/Lok Sabha Data/Location data/LS16_plot_data.csv')

In [ ]:
trial = pd.concat([english_coordinates, hindi_coordinates])

In [ ]:
trial.reset_index(inplace=True)

In [ ]:
trial.drop(['Unnamed: 0'], inplace=True, axis=1)

In [ ]:
trial.drop(['index'], inplace=True, axis=1)

In [ ]:
trial

             actual_address  ... Frequency
0               Maharashtra  ...    1165.0
1                 Rajasthan  ...     640.0
2                    States  ...    5673.0
3     the Union Territories  ...      47.0
4                 Karnataka  ...    1725.0
...                     ...  ...       ...
8235                 जर्मनी  ...       NaN
8236                   दुबई  ...       NaN
8237                 दिल्ली  ...       NaN
8238                  कस्बा  ...       NaN
8239                  पट्टी  ...       NaN

[8240 rows x 5 columns]

In [ ]:
trial.to_csv('/content/drive/MyDrive/Lok Sabha Data/Location data/plot_data_all_locations.csv')